### PR TITLE
Les 23

### PR DESCRIPTION
**Pull request by IgorTanov**
rework display logIn and reg

### CODE REVIEW

**Review by Evgeniy121212 — COMMENTED** [review]
Please, remove "lessoner_project_frontend" submodule

image
 
(the first one at the image above)

**Comment by IgorTanov** [comment]
remove lessoner_project_frontend

**Review by Evgeniy121212 — APPROVED** [review]

**Comment by Evgeniy121212** [comment]
Please, update this PR with changes from `develop`

**Review by valer-sky — APPROVED** [review]

**Comment by Evgeniy121212** [comment]
@IgorTanov, please, close that PR if it's not needed

Thanks!

**Pull request closed without merging**
